version: "3"

services:
  lolz-fpm:
    image: "ghcr.io/brbkaffe/lolz:fpm"
    volumes:
      - './data:/var/www/lolz/data'
    environment:
      APP_ENV: "prod"

  nginx:
    image: 'ghcr.io/brbkaffe/lolz:proxy'
    ports:
      - "8000:80"

  cron:
    image: 'ghcr.io/brbkaffe/lolz:cron'
    volumes:
      - './data:/app/data'
    environment:
      APP_ENV: "prod"
