version: "3"

services:
  php:
    image: "registry.digitalocean.com/brbcoffee/site:lolz-fpm"
    volumes:
      - './data:/var/www/lolz/data'
    environment:
      APP_ENV: "prod"

  nginx:
    image: 'registry.digitalocean.com/brbcoffee/site:lolz-proxy'
    ports:
      - 80:80

  cron:
    image: 'registry.digitalocean.com/brbcoffee/site:lolz-cron'
    volumes:
      - './data:/app/data'
    environment:
      APP_ENV: "prod"
