version: "3"

services:
  php:
    build:
      context: "./"
      dockerfile: "./dockerfiles/Dockerfile"
      target: fpm
    image: "brbcoffee/lolz-fpm"
    volumes:
      - './data:/var/www/project/data'
    environment:
      APP_ENV: "prod"

  nginx:
    build:
      context: "./"
      dockerfile: "./dockerfiles/Dockerfile"
      target: proxy
    image: 'brbcoffee/lolz-nginx'
    ports:
      - 80:80
    environment:
      APP_ENV: "prod"

  cron:
    build:
      context: "./"
      dockerfile: "./dockerfiles/Dockerfile"
      target: cron
    image: 'brbcoffee/lolz-cron'
    volumes:
      - './data:/app/data'