version: "3"

services:
  lolz-fpm:
    image: "ghcr.io/snoensoftware/lolz:fpm"
    volumes:
      - "./data:/var/www/lolz/data"
    environment:
      APP_ENV: "prod"

  nginx:
    image: "ghcr.io/snoensoftware/lolz:proxy"
    ports:
      - "8000:80"

  cron:
    image: "ghcr.io/snoensoftware/lolz:cron"
    volumes:
      - "./data:/app/data"
    environment:
      APP_ENV: "prod"
