version: "3"

services:
  php:
    image: "ghcr.io/bjornsnoen/lolz/fpm:latest"
    volumes:
      - './data:/var/www/lolz/data'
    environment:
      APP_ENV: "prod"

  nginx:
    image: 'ghcr.io/bjornsnoen/lolz/proxy:latest'
    ports:
      - 8000:80

  cron:
    image: 'ghcr.io/bjornsnoen/lolz/cron:latest'
    volumes:
      - './data:/app/data'
    environment:
      APP_ENV: "prod"
