name: prod-proxy

on:
  workflow_run:
    workflows:
      - "docker-push"
    types:
      - completed


jobs:
  prod-proxy:
    name: Update prod proxy image
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          repository: brbkaffe/brbcoffeespace
          event-type: lolz-update
